/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam.instituto.vista;

import dam.instituto.controller.Controller;

/**
 *
 * @author alvar
 */
public class FormPrincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form menu
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmInicio = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();
        jmAlumno = new javax.swing.JMenu();
        jmAdministrarAlumno = new javax.swing.JMenuItem();
        jmMostrarAlumno = new javax.swing.JMenuItem();
        jmMatricula = new javax.swing.JMenu();
        jmAdministrarMatricula = new javax.swing.JMenuItem();
        jmMostrarMatricula = new javax.swing.JMenuItem();
        jmAsignatura = new javax.swing.JMenu();
        jmAdministrarAsignatura = new javax.swing.JMenuItem();
        jmMostrarAsignatura = new javax.swing.JMenuItem();
        jmNotas = new javax.swing.JMenu();
        jmAdministrarNota = new javax.swing.JMenuItem();
        jmCalificar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instituto Publico Almirante");
        setBackground(new java.awt.Color(255, 255, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Secretaria Instituto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 161, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 119, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 120, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 255, 255));

        jmInicio.setBackground(new java.awt.Color(0, 204, 255));
        jmInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jmInicio.setForeground(new java.awt.Color(255, 255, 255));
        jmInicio.setText("INICIO");
        jmInicio.setToolTipText("");
        jmInicio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmSalir.setBackground(new java.awt.Color(0, 204, 255));
        jmSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmSalir.setForeground(new java.awt.Color(255, 255, 255));
        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jmInicio.add(jmSalir);

        jMenuBar1.add(jmInicio);

        jmAlumno.setBackground(new java.awt.Color(0, 204, 255));
        jmAlumno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jmAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jmAlumno.setText("ALUMNO");
        jmAlumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmAdministrarAlumno.setBackground(new java.awt.Color(0, 204, 255));
        jmAdministrarAlumno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmAdministrarAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jmAdministrarAlumno.setText("Administrar Alumno");
        jmAdministrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdministrarAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmAdministrarAlumno);

        jmMostrarAlumno.setBackground(new java.awt.Color(0, 204, 255));
        jmMostrarAlumno.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmMostrarAlumno.setForeground(new java.awt.Color(255, 255, 255));
        jmMostrarAlumno.setText("Mostrar Alumnos");
        jmMostrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMostrarAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmMostrarAlumno);

        jMenuBar1.add(jmAlumno);

        jmMatricula.setBackground(new java.awt.Color(0, 204, 255));
        jmMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jmMatricula.setForeground(new java.awt.Color(255, 255, 255));
        jmMatricula.setText("MATRICULA");
        jmMatricula.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmAdministrarMatricula.setBackground(new java.awt.Color(0, 204, 255));
        jmAdministrarMatricula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmAdministrarMatricula.setForeground(new java.awt.Color(255, 255, 255));
        jmAdministrarMatricula.setText("Administrar Matricula");
        jmAdministrarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdministrarMatriculaActionPerformed(evt);
            }
        });
        jmMatricula.add(jmAdministrarMatricula);

        jmMostrarMatricula.setBackground(new java.awt.Color(0, 204, 255));
        jmMostrarMatricula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmMostrarMatricula.setForeground(new java.awt.Color(255, 255, 255));
        jmMostrarMatricula.setText("Mostrar Matriculas");
        jmMostrarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMostrarMatriculaActionPerformed(evt);
            }
        });
        jmMatricula.add(jmMostrarMatricula);

        jMenuBar1.add(jmMatricula);

        jmAsignatura.setBackground(new java.awt.Color(0, 204, 255));
        jmAsignatura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jmAsignatura.setForeground(new java.awt.Color(255, 255, 255));
        jmAsignatura.setText("ASIGNATURA");
        jmAsignatura.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmAdministrarAsignatura.setBackground(new java.awt.Color(0, 204, 255));
        jmAdministrarAsignatura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmAdministrarAsignatura.setForeground(new java.awt.Color(255, 255, 255));
        jmAdministrarAsignatura.setText("Administrar Asignatura");
        jmAdministrarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdministrarAsignaturaActionPerformed(evt);
            }
        });
        jmAsignatura.add(jmAdministrarAsignatura);

        jmMostrarAsignatura.setBackground(new java.awt.Color(0, 204, 255));
        jmMostrarAsignatura.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmMostrarAsignatura.setForeground(new java.awt.Color(255, 255, 255));
        jmMostrarAsignatura.setText("Mostrar Asignaturas");
        jmMostrarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMostrarAsignaturaActionPerformed(evt);
            }
        });
        jmAsignatura.add(jmMostrarAsignatura);

        jMenuBar1.add(jmAsignatura);

        jmNotas.setBackground(new java.awt.Color(0, 204, 255));
        jmNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jmNotas.setForeground(new java.awt.Color(255, 255, 255));
        jmNotas.setText("Notas Alumnos");
        jmNotas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jmAdministrarNota.setBackground(new java.awt.Color(0, 204, 255));
        jmAdministrarNota.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmAdministrarNota.setForeground(new java.awt.Color(255, 255, 255));
        jmAdministrarNota.setText("Ver notas Alumno");
        jmAdministrarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAdministrarNotaActionPerformed(evt);
            }
        });
        jmNotas.add(jmAdministrarNota);

        jmCalificar.setBackground(new java.awt.Color(0, 204, 255));
        jmCalificar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmCalificar.setForeground(new java.awt.Color(255, 255, 255));
        jmCalificar.setText("Calificar Alumno");
        jmCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCalificarActionPerformed(evt);
            }
        });
        jmNotas.add(jmCalificar);

        jMenuBar1.add(jmNotas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMostrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMostrarAlumnoActionPerformed
        FormDatosAlumno formularioDatosAlumno = new FormDatosAlumno(this, true);
        formularioDatosAlumno.setVisible(true);
    }//GEN-LAST:event_jmMostrarAlumnoActionPerformed

    private void jmMostrarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMostrarMatriculaActionPerformed
        FormDatosMatricula formularioDatosMatricula = new FormDatosMatricula(this, true);
        formularioDatosMatricula.setVisible(true);
    }//GEN-LAST:event_jmMostrarMatriculaActionPerformed

    private void jmMostrarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMostrarAsignaturaActionPerformed
        FormDatosAsignatura formularioDatosAsignatura = new FormDatosAsignatura(this, true);
        formularioDatosAsignatura.setVisible(true);
    }//GEN-LAST:event_jmMostrarAsignaturaActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmAdministrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAdministrarAlumnoActionPerformed
        FormAlumno formularioAlumno = new FormAlumno(this, true);
        formularioAlumno.setVisible(true);
    }//GEN-LAST:event_jmAdministrarAlumnoActionPerformed

    private void jmAdministrarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAdministrarMatriculaActionPerformed
        FormMatricula formularioMatricula = new FormMatricula(this, true);
        formularioMatricula.setVisible(true);
    }//GEN-LAST:event_jmAdministrarMatriculaActionPerformed

    private void jmAdministrarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAdministrarAsignaturaActionPerformed
        FormAsignatura formularioAsignatura =  new FormAsignatura(this, true);
        formularioAsignatura.setVisible(true);
    }//GEN-LAST:event_jmAdministrarAsignaturaActionPerformed

    private void jmAdministrarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAdministrarNotaActionPerformed
        FormNotasAlumno formularioNotasAlumno = new FormNotasAlumno(this, true);
        formularioNotasAlumno.setVisible(true);
    }//GEN-LAST:event_jmAdministrarNotaActionPerformed

    private void jmCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCalificarActionPerformed
        FormCalificarAlumno formCalificarAlumno = new FormCalificarAlumno(this, true);
        formCalificarAlumno.setVisible(true);
    }//GEN-LAST:event_jmCalificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmAdministrarAlumno;
    private javax.swing.JMenuItem jmAdministrarAsignatura;
    private javax.swing.JMenuItem jmAdministrarMatricula;
    private javax.swing.JMenuItem jmAdministrarNota;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmAsignatura;
    private javax.swing.JMenuItem jmCalificar;
    private javax.swing.JMenu jmInicio;
    private javax.swing.JMenu jmMatricula;
    private javax.swing.JMenuItem jmMostrarAlumno;
    private javax.swing.JMenuItem jmMostrarAsignatura;
    private javax.swing.JMenuItem jmMostrarMatricula;
    private javax.swing.JMenu jmNotas;
    private javax.swing.JMenuItem jmSalir;
    // End of variables declaration//GEN-END:variables
}
